#!/usr/bin/env sh

input_message="$(cat $1)"
commit_message_regex="^(feat|fix|docs|style|refactor|test|chore|revert|build|perf|ops)(\(\S+\))?: .+$"

# Use grep instead of [[ for compatibility reasons.
# The dash shell, which is standard for Debian and Ubuntu, doesn’t support it.

if ! echo "$input_message" | grep -E -q "$commit_message_regex"; then
  echo "-"
  echo "-"
  echo "Error: the commit message didn't pass the format check."
  echo "Expected format: <verb><optional scope><semicolon><whitespace><short headline of what changed>"
  echo "Received message: $input_message"
  echo "For more information consult the pre-commit script."
  echo "-"
  echo "-"
  exit 1
fi
