#!/usr/bin/env sh

message="$(cat $1)"
requiredPattern="^(feat|fix|docs|style|refactor|test|chore|revert|build|perf|ops)(\([^)]+\))?: .*$"

if [ "$message" = *"$requiredPattern"* ]; then
  echo "-"
  echo "-"
  echo "-"
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "<verb><optional scope><semicolon> <short headline of what changed>"
  echo "Allowed verbs: add, remove, update, fix, docs, style, refactor, test, chore"
  echo "Example: feat: login button"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  echo "For more information, check script in .husky/commit-msg"
  echo "-"
  exit 1
fi
