name: Update code coverage

on:
  push:
    # Release branch doesn't need the coverage update. The update can be made only on dev branch.
    branches: ['dev']

permissions:
  contents: write

jobs:
  update-coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.14.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.22.0

      - run: pnpm i
        working-directory: ./apps/mobile

      - name: Get coverage and update readme
        working-directory: ./apps/mobile
        run: |
          pnpm run test --coverage --coverageDirectory="${{ runner.temp }}" --coverageReporters="json-summary"
          total_cov="$(jq .total.lines.pct ${{ runner.temp }}/coverage-summary.json)"
          sed -i "s/coverage-\(.*\)%/coverage-${total_cov}%/" ../../README.md

      - name: Commit and push changes if README.md was changed by the previous step.
        if: contains(github.event.push.changed_files, '../../README.md')
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@${{ github.actor.email}}"
          git add .
          git commit -m 'chore: update coverage'
          git push
