# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Update code coverage

on:
  push:
    # It is supposed to work on only dev branch
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - name: Get coverage and update readme
        run: |
          npm test -- --coverage --coverageDirectory="${{ runner.temp }}" --coverageReporters="json-summary"
          total_cov="$(jq .total.lines.pct ${{ runner.temp }}/coverage-summary.json)"
          sed -i "s/coverage-\(.*\)%/coverage-${total_cov}%/" ./README.md
      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m 'chore: update coverage'
          git push
