name: Test

on:
  # TODO: push is temp; PR
  push:
    branches: ['dev', 'release']

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.14.0]

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10.22.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # cache: "pnpm"

      - run: pnpm i
        working-directory: ./apps/mobile
      - run: pnpm run test
        working-directory: ./apps/mobile
